#!/usr/bin/env python3
"""
GIF → LVGL C Array Converter
GIF dosyasını LVGL lv_image_dsc_t uyumlu C array'e çevirir.
LVGL'nin dahili GIF decoder'ı (LV_USE_GIF=1) ham binary formatı kullanır.
"""

import os
import sys

INPUT  = os.path.expanduser("~/Masaüstü/dedsec_themed.gif")
OUTPUT = os.path.expanduser("~/Masaüstü/xiaozhieyes/WDGWatch/src/ui/dedsec_gif.c")
HEADER = os.path.expanduser("~/Masaüstü/xiaozhieyes/WDGWatch/src/ui/dedsec_gif.h")

def main():
    if not os.path.exists(INPUT):
        print(f"[HATA] Dosya bulunamadı: {INPUT}")
        sys.exit(1)

    with open(INPUT, "rb") as f:
        data = f.read()

    size = len(data)
    print(f"[OK] GIF okundu: {size} bytes ({size/1024:.1f} KB)")

    # C array oluştur
    hex_lines = []
    for i in range(0, size, 16):
        chunk = data[i:i+16]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        hex_lines.append(f"    {hex_str},")

    c_content = f"""/* Auto-generated by gif_to_c_array.py — DO NOT EDIT */
/* Source: dedsec_themed.gif | {size} bytes | WDGWatch SCR Terminal Theme */

#include "dedsec_gif.h"

const uint8_t dedsec_gif_data[{size}] = {{
{chr(10).join(hex_lines)}
}};

const lv_image_dsc_t dedsec_gif = {{
    .header = {{
        .magic     = LV_IMAGE_HEADER_MAGIC,
        .cf        = LV_COLOR_FORMAT_RAW,
        .flags     = 0,
        .w         = 220,
        .h         = 220,
        .stride    = 0,
    }},
    .data_size = {size},
    .data      = dedsec_gif_data,
}};
"""

    h_content = f"""/* Auto-generated by gif_to_c_array.py — DO NOT EDIT */
#pragma once
#include <lvgl.h>

extern const uint8_t dedsec_gif_data[{size}];
extern const lv_image_dsc_t dedsec_gif;
"""

    with open(OUTPUT, "w") as f:
        f.write(c_content)
    with open(HEADER, "w") as f:
        f.write(h_content)

    print(f"[OK] C array  → {OUTPUT}")
    print(f"[OK] Header   → {HEADER}")
    print(f"[DONE] LVGL GIF asset hazır.")

if __name__ == "__main__":
    main()
